# 01 머신러닝

## 내장된 예제 데이터셋

In [4]:
# 붓꽃 데이터셋 생성

from sklearn.datasets import load_iris

iris = load_iris()
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [5]:
# Bunch 클래스; 딕셔너리 자료형과 유사
# 따라서 key 값 확인

keys = iris.keys()
print('붓꽃 데이터셋의 키:', keys)

붓꽃 데이터셋의 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
# 각 키가 가리키는 값 확인

# feature_names
print('feature_names의 type:', type(iris.feature_names))
print('feature_names의 shape:', len(iris.feature_names))
print(iris.feature_names)

# target_names
print('\n target_names의 type:', type(iris.target_names))
print('target_names의 shape:', len(iris.target_names))
print(iris.target_names)

# data
print('\n data의 type:', type(iris.data))
print('data의 shape:', len(iris.data))
print(iris.data)

# target
print('\n target의 type:', type(iris.target))
print('target의 shape:', len(iris.target))
print(iris.target)

feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: 150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3

## 사이킷런을 이용한 머신러닝 실습

In [1]:
# 사이킷런 버전 확인

import sklearn
sklearn.__version__

'0.23.2'

In [ ]:
# 붓꽃의 품종 '분류(Classification)' 문제
# Y: 붓꽃의 품종(Setosa, Vesicolor, Virginica)
# X: 꽃잎 길이, 꽃잎 너비, 꽃받침 길이, 꽃받침 너비 

# 0. 데이터셋 준비 및 관련 모듈 로드
# 1. 데이터셋 분리: 학습데이터와 테스트데이터로 분리 -> train_test_split()
# 2. 모델 학습: 학습데이터에 ML 알고리즘을 적용해 모델 학습 -> fit()
# 3. 예측 수행: 학습된 모델을 이용해 테스트데이터에 적용해 예측 -> predict()
# 4. 평가: 예측된 결과값과 테스트데이터의 실제값을 비교하여 모델 성능 평가 -> accuracy_score()

In [1]:
# 0. 데이터셋 준비 및 관련 모듈 로드

#붓꽃 데이터셋 
from sklearn.datasets import load_iris 
#ML 알고리즘으로 의사결정트리(Decision Tree) 알고리즘 수행하기 위한 클래스
from sklearn.tree import DecisionTreeClassifier 
#데이터 세트를 학습 데이터와 테스트 데이터로 분리하기 위한 API
from sklearn.model_selection import train_test_split 
#데이터 처리를 위한 라이브러리
import pandas as pd

#붓꽃 데이터 세트 로딩
iris = load_iris()

#iris_data는 Iris 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target 값 :', iris_label)
print('iris target 명 :', iris.target_names) #iris.target_names는 레이블에 해당하는 이름

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df =pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 : ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [12]:
# 1. 데이터셋 분리
# train_test_split(feature_data_set, label_data_set, test_size, random_state) 
# 피처 데이터 세트로 iris_data, 레이블 데이터로 iris_lable 이용

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [13]:
# 2. 모델 학습

# DecisionTreeClassifier 객체 생성
# random_state=11역시 예제 코드 수행시마다 동일한 학습/ 예측 결과를 출력하기 위한 용도
dt_clf = DecisionTreeClassifier(random_state=11)

# DecisionTreeClassifier 객체는 학습 데이터를 기반으로 학습 완료
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [18]:
# 3. 예측 수행
# 예측은 반드시 학습 데이터가 아닌 다른 데이터를 이용, 일반적으로 테스트 데이터 세트를 이용
# DecisionTreeClassifier 객체의 predict() 메서드에 테스트용 피처 데이터 세트를 입력하면 
# 학습된 모델 기반에서 테스트 데이터 세트에 대한 예측값을 반환

# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [19]:
# 4. 평가
# 예측 결과를 기반으로 의사 결정 트리 기반 모델의 예측 성능을 평가
# 머신러닝 모델의 성능 평가 방법은 여러 가지가 있으나 여기서는‘정확도' 측정

# accuracy_score은 사이킷런에서 정확도 측정을 위해 제공하는 함수
from sklearn.metrics import accuracy_score

# y_test: 실제값, pred: 예측값
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


# 02 교차검증

## K-fold 

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [12]:
# iris 데이터셋과 DecisionTreeClassifier 생성하기
iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

In [13]:
# 5개의 폴드 세트로 분리하는 kfold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy= []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [20]:
n_iter = 0

# kfold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    # 반복마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
         .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


## Stratified K-fold 

In [22]:
# iris data의 레이블 분포 확인
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts() # 레이블 0, 1, 2 모두 50개로 동일

2    50
1    50
0    50
Name: label, dtype: int64

In [25]:
# kfold 교차검증 시 레이블 분포도

kfold = KFold(n_splits = 3)
n_iter = 0

for train_index , test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포: \n', label_train.value_counts())
    print('검증 레이블 데이터 분포: \n', label_test.value_counts())
    
# 교차검증 시마다 3개의 폴드 세트로 만들어지는 학습레이블과 검증레이블이 완전히 다르게 추출 
# 즉, 검증 예측 정확도 0

## 교차검증: 1
학습 레이블 데이터 분포: 
 2    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64
## 교차검증: 2
학습 레이블 데이터 분포: 
 2    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64
## 교차검증: 3
학습 레이블 데이터 분포: 
 1    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64


In [26]:
# stratified kfold 교차검증 시 레이블 분포도

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

# StratifiedKFold 에서는 데이터셋과 함께 label값을 같이 넘겨야한다.
for train_index , test_index in skf.split(iris_df , iris_df['label']):
    n_iter +=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print('## 교차검증 : {0}'.format(n_iter))
    print('학습 레이블 데이터 분포 \n',label_train.value_counts())
    print('검증 레이블 데이터 분포 \n',label_test.value_counts())
    
# 학습 레이블과 검증 레이블 데이터의 분포도가 동일하게 할당됨
# 즉, 전체 레이블값의 분포도를 고려하는 교차검증 방법

## 교차검증 : 1
학습 레이블 데이터 분포 
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포 
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차검증 : 2
학습 레이블 데이터 분포 
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포 
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차검증 : 3
학습 레이블 데이터 분포 
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포 
 2    17
1    17
0    16
Name: label, dtype: int64


In [27]:
# stratified kfold 교차검증 수행 및 정확도 계산

iris = load_iris()
features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 셋도 추가 입력 해야한다.
for train_index , test_index in skfold.split(features , label):
    
    # split()으로 반환된 인덱스를 이용하여 학습용 , 검증용 테스트 데이터 추출
    X_train , X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    # 학습및 예측
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    
    
    # 반복시 마다 정확도 측정
    n_iter +=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도 : {1} , 학습데이터 크기 {2} , 검증데이터 크기 : {3} '
          .format(n_iter , accuracy , train_size , test_size))
    print('\n#{0} 검증 세트 인덱스 : {1}'.format(n_iter , test_index))
    print('=============================================================\n')
    cv_accuracy.append(accuracy)
    
print("\n## 교차 검증별 정확도: ", np.round(cv_accuracy,4))
print("\n## 평균 검증 정확도: ", np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.98 , 학습데이터 크기 100 , 검증데이터 크기 : 50 

#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]


#2 교차 검증 정확도 : 0.94 , 학습데이터 크기 100 , 검증데이터 크기 : 50 

#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]


#3 교차 검증 정확도 : 0.98 , 학습데이터 크기 100 , 검증데이터 크기 : 50 

#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


## 교차 검증별 정확도:  [0.98 0.94 0.98]

## 평균 검증 정확도:  0.9666666666666667


In [ ]:
# estimator가 Regressor(회귀); K-fold 이용
# estimator가 Classifier(분류); Stratified K-fold 이용

## Cross_val_score

In [28]:
# cross_val_score()
# 교차검증을 조금 더 편리하게 수행하는 기능
# k-fold로 데이터를 학습하고 예측하는 과정을 한번에 수행

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도 (accuracy) , 교차 검증 세트 3개
scores = cross_val_score(dt_clf , data, label, scoring='accuracy', cv=3)
print(scores)
print("교차 검증별 정확도", np.round(scores, 4))
print("평균 검증 정확도", np.round(np.mean(scores), 4))

[0.98 0.94 0.98]
교차 검증별 정확도 [0.98 0.94 0.98]
평균 검증 정확도 0.9667


## GridSearchCV

In [29]:
# GridSearchCV()
# 교차검증과 하이퍼파라미터 튜닝을 한 번에 가능
# 하이퍼파라미터로 적용해볼 값들을 미리 정하여 모든 조합을 시행

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV , train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

iris = load_iris()

# 학습데이터와 테스트 데이터로 분리
X_train , X_test , y_train , y_test = train_test_split(iris.data , iris.target,
                                                      test_size = 0.2 , random_state =121)

dtree = DecisionTreeClassifier()

# parameter 들을 dictionary 형태로 설정
parameters = {'max_depth' : [1,2,3] , 'min_samples_split':[2,3]}

import pandas as pd

# param_grid의 하이퍼 파라미터들을 3개의 train, test set fold로 나누어서 테스트 수행 설정
## refit = True 가 default임  True 면 가장 좋은 파라미터 설정으로 재 학습 시킴
grid_dtree = GridSearchCV(dtree , param_grid=parameters, cv=3 ,refit=True , return_train_score=True)

# iris Train 데이터로 param_grid의 하이퍼 파라미터들을 순차적으로 학습/평가
grid_dtree.fit(X_train , y_train)

print("grid_dtree" , grid_dtree)

#GridSearchCV 결과는 cv_results 라는 딕셔너리로 저장됨 이를 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score', 'rank_test_score', 'split0_test_score','split1_test_score', 'split2_test_score']]

grid_dtree GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},
             return_train_score=True)


params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [30]:
print("GridSearchCV 최적 파라미터 : " , grid_dtree.best_params_)
print("GridSearchCV 최고 정확도 : {0:.4f}" .format(grid_dtree.best_score_))

# refit =True로 설정된 GridSearchCV 객체가 fit()을 수행시 학습이 완료된 Estimator를 내포하고있으므로 predict()를 통해 예측도 가능
pred = grid_dtree.predict(X_test)
 
print("테스트 데이터 세트 정확도 : {0:.4f}".format(accuracy_score(y_test,pred)))

GridSearchCV 최적 파라미터 :  {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 : 0.9750
테스트 데이터 세트 정확도 : 0.9667


## RandomSearchCV

In [37]:
# RandomizedSearchCV()
# 범위 내 무작위 값 추출을 통한 하이퍼파라미터 튜닝 방법
# GridSearchCV 보다 훨씬 다양한 조합들을 시험할 수 있음
# n_iter 값만큼 반복

from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

# breast_cancer 데이터 생성 및 train_test_split
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, stratify=data.target, random_state=66)

In [38]:
# 하이퍼파라미터 튜닝 이전 모델 성능
tree = DecisionTreeClassifier(random_state=0)
tree.fit(X_train, y_train)

print(tree.score(X_test, y_test))

0.8951048951048951


In [41]:
# by GridSerchCV

dt = DecisionTreeClassifier(random_state=0)

param_grid = {'criterion': ['gini', 'entropy'],
             'max_depth': [4,5,6,8,10],
             'min_samples_leaf': [3,5,10,50,100]}

gcv = GridSearchCV(dt, param_grid = param_grid, cv=3, scoring='accuracy', n_jobs=-1)
gcv.fit(X_train, y_train)

print('final params', gcv.best_params_)
print('best score', gcv.best_score_)
print(gcv.score(X_test, y_test))

final params {'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 3}
best score 0.9460093896713615
0.916083916083916


In [44]:
# by RandomSearchCV

dt = DecisionTreeClassifier(random_state=0)

param_grid = {'criterion': ['gini', 'entropy'],
             'max_depth': [3,10],
             'min_samples_leaf': [3,100]}

rcv = RandomizedSearchCV(dt, param_distributions = param_grid, cv=3, scoring='accuracy', n_iter=5)
rcv.fit(X_train, y_train)

print('final params', rcv.best_params_)
print('best score', rcv.best_score_)
print(rcv.score(X_test, y_test))

final params {'min_samples_leaf': 3, 'max_depth': 3, 'criterion': 'gini'}
best score 0.9460093896713615
0.9230769230769231


In [45]:
# 비교; randomsearch가 가장 우수!

print('기존 모델 성능:', tree.score(X_test, y_test))
print('GridSearchCV 모델 성능:', gcv.score(X_test, y_test))
print('RandomSearchCV 모델 성능:', rcv.score(X_test, y_test))

기존 모델 성능: 0.8951048951048951
GridSearchCV 모델 성능: 0.916083916083916
RandomSearchCV 모델 성능: 0.9230769230769231


# 03 데이터 전처리

## 데이터 인코딩

* 문자열, 범주형 데이터 등의 데이터를 컴퓨터가 이해할 수 있는 수치형 데이터로 변환

### 레이블 인코딩

In [2]:
# 레이블 인코딩; LabelEncoder -> fit(), transform()

from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터',
         '선풍기','선풍기', '믹서', '믹서']

# LabelEncoder 객체 생성
encoder = LabelEncoder()

# Label Encoding 수행 
encoder.fit(items)
labels = encoder.transform(items)

In [2]:
# 인코딩 결과 확인
print('레이블 인코딩 변환값:', labels)

레이블 인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
# 데이터 값이 많을 경우; LabelEncoder.classes_
print('레이블 인코딩 클래스:', encoder.classes_)

레이블 인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [4]:
# 디코딩; LabelEncoder.inverse_transform()
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원-핫 인코딩

In [3]:
# 원-핫 인코딩; OneHotEncoder -> fit(), transform()
# 원-핫 인코딩 조건 
# 1) 숫자형 변수
# 2) 2차원 데이터

from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Label Encoding; 먼저 숫자형 데이터로 변환
encoder = LabelEncoder() 
encoder.fit(items)
labels = encoder.transform(items)

# reshape; 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# One-Hot Encoding
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels) 
oh_labels = oh_encoder.transform(labels)

In [6]:
# 원-핫 인코딩된 데이터
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [15]:
# 원-핫 인코딩 데이터 차원
oh_labels.shape

(8, 6)

In [4]:
# cf. 원-핫 인코딩 by Pandas
# get_dummies(); 숫자형 변환 필요없이 바로 가능  

import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터',
                           '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## 피처 스케일링과 정규화

### StandardScaler

In [5]:
# iris 데이터셋 준비

from sklearn.datasets import load_iris
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data
            , columns=iris.feature_names)

In [6]:
# 원본 데이터 확인 

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
# StandardScaler; 평균 0, 분산 1인 정규분포를 따르도록 변환

from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터셋 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) 

# Numpy ndarray -> DataFrame 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled
                     , columns=iris.feature_names)

In [21]:
# 변환 후 데이터 확인 

print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler

In [22]:
# MinMaxScaler; 0~1 사이 값으로 변환 

from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터셋 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# Numpy ndarray -> DataFrame 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled
                  , columns=iris.feature_names)

In [23]:
# 변환 후 데이터 확인 

print('feature들의 최소값')
print(iris_df_scaled.min())
print('\nfeature들의 최대값')
print(iris_df_scaled.max())

feature들의 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 데이터 스케일링 유의점

In [28]:
# 학습데이터/테스트데이터 생성 + 2차원 데이터로 변환
train_array = np.arange(0,11).reshape(-1,1) # 0~10
test_array = np.arange(0,6).reshape(-1,1) # 0~5

In [26]:
# 학습데이터 변환; fit() + transform()

# 별도의 파라미터를 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

# fit(); train_array의 최소값이 0, 최대값이 10으로 설정됨
scaler.fit(train_array)

# transform(); 1/10 scale로 train_array 변환
train_scaled = scaler.transform(train_array)

# 변환된 데이터 확인
print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scaled train_array 데이터:', np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [29]:
# 테스트데이터 변환; fit() + transform() - X 

# fit(); test_array의 최소값이 0, 최대값이 5으로 설정됨
scaler.fit(test_array)

# transform(); 1/5 scale로 test_array 변환
test_scaled = scaler.transform(test_array)

# 변환된 데이터 확인
print('원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('Scaled test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scaled test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [30]:
# 테스트데이터 변환; transform() - O

# 학습데이터 스케일링
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scaled train_array 데이터:', np.round(train_scaled.reshape(-1),2))

# 테스트데이터 스케일링
test_scaled = scaler.transform(test_array) # 바로 transform() 적용

print('원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('Scaled test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터: [0 1 2 3 4 5]
Scaled test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]


# 04 타이타닉 생존자 예측

In [1]:
# 타이타닉 데이터 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

titanic_df = pd.read_csv('C:/Users/USER/BITAmin/data/titanic_train.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [ ]:
# 타이타닉 데이터 정보 확인 
print('\n ### 학습 데이터 정보 ###  \n')
print(titanic_df.info())

In [ ]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace = True)
titanic_df['Cabin'].fillna('N', inplace = True)
titanic_df['Embarked'].fillna('N', inplace = True)
print('데이터 세트 Null 값 개수', titanic_df.isnull().sum().sum())

In [ ]:
print(' Sex 값 분포 :\n', titanic_df['Sex'].value_counts())
print('\n Cabin 값 분포 :\n', titanic_df['Cabin'].value_counts())
print('\n Embarked 값 분포 :\n', titanic_df['Embarked'].value_counts())

In [ ]:
# 데이터 전처리 관련 함수 정의

from sklearn.preprocessing import LabelEncoder

# Null 처리 함수
def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace  = True)
    df['Cabin'].fillna('N', inplace = True)
    df['Embarked'].fillna('N', inplace = True)
    df['Fare'].fillna(0, inplace = True)
    return df

# 머신러닝 알고리즘에 불필요한 속성 제거
def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1 , inplace = True)
    return df

# 레이블 인코딩 수행.
def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

# 앞에서 설정한 데이터 전처리 함수 호출
def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    
    return df

In [ ]:
# 성별에 따라서 생존이 갈렸는지를 확인해보자. 0은 사망, 1은 생존
titanic_df.groupby(['Sex', 'Survived'])['Survived'].count()

In [ ]:
# 이를 시각화 데이터로 표현
sns.barplot(x = 'Sex', y = 'Survived', data = titanic_df)

In [ ]:
# 객실 등급에 따른 생존확률
sns.barplot(x = 'Pclass', y = 'Survived', hue = 'Sex',data = titanic_df)

In [ ]:
# Age에 따른 구분 값을 반환하는 함수 설정. DataFrame의 apply lambda사용

def get_category(age):
    cat = ''
    if age <= -1 : cat = 'Unknown'
    elif age <= 5 : cat = 'Baby'
    elif age <= 12 : cat = 'Child'
    elif age <= 18 : cat = 'Teenager'
    elif age <= 25 : cat = 'Student'
    elif age <= 35 : cat = 'Young Adult'
    elif age <= 60 : cat = 'Adult'
    else : cat = 'Elderly'
    return cat

# 막대그래프의 크기 figure를 더 크게 설정
plt.figure(figsize=(10,6))

# X축의 값을 순차적으로 표시하기 위한 설정
group_names = ['Uknown', 'Baby', 'Child', 'Teenager', 'Student', 'Young Adult', 'Adult', 'Elderly']

# lambda 식에 위에서 생성한 get_category()함수를 반환값으로 지정
# get_category(X)는 입력값으로 'Age'칼럼 값을 받아서 해당하는 cat반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
sns.barplot(x = 'Age_cat', y = 'Survived', hue = 'Sex' , data = titanic_df, order=group_names)
titanic_df.drop('Age_cat', axis = 1, inplace = True)

In [ ]:
# 원본 데이터를 재로딩하고, 피처 데이터 세트와 레이블 데이터 세트 추출
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived', axis = 1)

X_titanic_df = transform_features(X_titanic_df)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size = 0.2, random_state= 11)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 결정트리, RandomForest, 로지스틱 회귀를 이용한 사이킷런 Classifier 클래스 생성
dt_clf = DecisionTreeClassifier(random_state = 11)
rf_clf = RandomForestClassifier(random_state = 11)
lr_clf = LogisticRegression()

# DecisionTreeClassifier 학습/예측/평ㅇ가
dt_clf.fit(X_train, y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도 :{0:.4f}'.format(accuracy_score(y_test, dt_pred)))

# RandomForestClassifier 학습/예측/평ㅇ가
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도 :{0:.4f}'.format(accuracy_score(y_test, rf_pred)))

# LogisticRegression 학습/예측/평ㅇ가
lr_clf.fit(X_train, y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도 :{0:.4f}'.format(accuracy_score(y_test, lr_pred)))

In [ ]:
from sklearn.model_selection import KFold

def exec_kfold(clf, folds = 5):
    # 폴드 세트를 5개인 KFold객체를 생성, 폴드 수만큼 예측결과 저장을 위한 리스트 객체 생성
    kfold = KFold(n_splits=folds)
    scores = []
    
    # KFold 교차 검증 수행.
    for iter_count, (train_index, test_index) in enumerate(kfold.split(X_titanic_df)):
        # X_titanic_df 데이터에서 교차 검증별로 학습과 검증 데이터를 가리키는 index생성
        X_train, X_test = X_titanic_df.values[train_index], X_titanic_df.values[test_index]
        y_train, y_test = y_titanic_df.values[train_index], y_titanic_df.values[test_index]
        # Classifier 학습, 예측 정확도 계산
        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        scores.append(accuracy)
        print("교차 검증 {0} 정확도 : {1:.4f}".format(iter_count, accuracy))
        
        
    mean_score = np.mean(scores)
    print("평균 정확도 : {0:.4f}".format(mean_score))

# exec_kfold호출
exec_kfold(dt_clf, folds = 5)

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_clf, X_titanic_df, y_titanic_df, cv = 5)
for iter_count, accuracy in enumerate(scores):
    print("교차 검증 {0} 정확도: {1:.4f}".format(iter_count, accuracy))
    
print("평균 정확도: {0:.4f}".format(np.mean(scores)))

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = {'max_depth': [2,3,5,10], 'min_samples_split':[2,3,5], 'min_samples_leaf':[1,5,8]}

grid_dclf = GridSearchCV(dt_clf, param_grid = parameters, scoring = 'accuracy', cv = 5)
grid_dclf.fit(X_train, y_train)

print('GridSearchCV 최적 하이퍼 파라미터 :', grid_dclf.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dclf.best_score_))
best_dclf = grid_dclf.best_estimator_

# GridSearchCV의 최적 하이퍼 파라미터로 학습된 Estimator로 예측 및 평가 수행.
dpredictions = best_dclf.predict(X_test)
accuracy = accuracy_score(y_test, dpredictions)
print('테스트 세트에서의 DecisionTreeClassifier 정확도 : {0:.4f}'.format(accuracy))
